version: "3"

services:
  db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  express-daem-app:
    image: abdohsn/express-daem-app
    container_name: daem_app
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    links:
      - db
    restart: on-failure
    depends_on:
      - db

volumes:
  mongodb-data:
